dist: trusty
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database spootest;' -U postgres
  - psql spootest < scripts/nametracking.sql
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install: "pip install -r requirements.txt"
script: pytest -vs
